server:
  port: ${PROJECT_PORT:8090}

spring:
  application:
    name: project-service

logging:
  level:
    ro.pdi.project: INFO
    org.springframework.web: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true